import Project1 from '../../src/assets/Project1.png';
import Project2 from '../../src/assets/Project2.png';
import Project3 from '../../src/assets/Project3.png';
import Project4 from '../../src/assets/Project4.png';
import Project5 from '../../src/assets/Project5.png';
import Project6 from '../../src/assets/Project6.png';
import Project7 from '../../src/assets/Project7.png';
import Project8 from '../../src/assets/Project8.png';
import Project9 from '../../src/assets/Project9.png';
import Project from '../../src/assets/Project.png';

export const projectsData = [
	// API Projects
	{
		id: 1,
		image: Project1,
		title: 'Node.js API with PostgreSQL',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/node-api-postgres',
		sourceUrl: 'https://github.com/JawherKl/node-api-postgres',
		status: 'completed',
	},
	{
		id: 2,
		image: Project5,
		title: 'API Design',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/api-design',
		sourceUrl: 'https://github.com/JawherKl/api-design',
		status: 'in-progress',
	},
	{
		id: 3,
		image: null,
		title: 'GraphQL Node.js E-commerce',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/graphql-nodejs-ecom',
		sourceUrl: 'https://github.com/JawherKl/graphql-nodejs-ecom',
		status: 'completed',
	},
	{
		id: 4,
		image: null,
		title: 'User Caching App',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/user-caching-app',
		sourceUrl: 'https://github.com/JawherKl/user-caching-app',
		status: 'completed',
	},
	{
		id: 5,
		image: null,
		title: 'Go User Caching',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/go-user-caching',
		sourceUrl: 'https://github.com/JawherKl/go-user-caching',
		status: 'completed',
	},
	{
		id: 6,
		image: null,
		title: 'Grpc Order Processing',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/grpc-order-process',
		sourceUrl: 'https://github.com/JawherKl/grpc-order-process',
		status: 'completed',
	},
	{
		id: 7,
		image: null,
		title: 'Go Crud GraphQL',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/go-crud-graphql',
		sourceUrl: 'https://github.com/JawherKl/go-crud-graphql',
		status: 'completed',
	},
	{
		id: 8,
		image: null,
		title: 'Kafka Go Microservices',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/kafka-go-microservices',
		sourceUrl: 'https://github.com/JawherKl/kafka-go-microservices',
		status: 'completed',
	},
	{
		id: 9,
		image: null,
		title: 'Kafka Go Microservices',
		category: 'API',
		demoUrl: 'https://github.com/JawherKl/api-gRPC',
		sourceUrl: 'https://github.com/JawherKl/api-gRPC',
		status: 'completed',
	},
	// Website Projects
	{
		id: 10,
		image: null,
		title: 'AI FAQ Bot',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/ai-faq-bot',
		sourceUrl: 'https://github.com/JawherKl/ai-faq-bot',
		status: 'completed',
	},
	{
		id: 11,
		image: null,
		title: 'Angular Guide',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/angular-guide',
		sourceUrl: 'https://github.com/JawherKl/angular-guide',
		status: 'completed',
	},
	{
		id: 12,
		image: Project7,
		title: 'Weather App',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/weather-app',
		sourceUrl: 'https://github.com/JawherKl/weather-app',
		status: 'in-progress',
	},
	{
		id: 13,
		image: Project7,
		title: 'DMARC Checker',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/dmarc-checker',
		sourceUrl: 'https://github.com/JawherKl/dmarc-checker',
		status: 'completed',
	},
	{
		id: 14,
		image: Project7,
		title: 'Simple Quiz App',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/simple-quiz-app',
		sourceUrl: 'https://github.com/JawherKl/simple-quiz-app',
		status: 'completed',
	},
	{
		id: 15,
		image: Project7,
		title: 'Portfolio',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/jawherkl.github.io',
		sourceUrl: 'https://github.com/JawherKl/jawherkl.github.io',
		status: 'in-progress',
	},
	{
		id: 16,
		image: Project7,
		title: 'Ngx Admin',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/ngx-admin',
		sourceUrl: 'https://github.com/JawherKl/ngx-admin',
		status: 'completed',
	},
	{
		id: 17,
		image: Project7,
		title: 'Angular Ng Select Customize',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/angular-ng-select-customize',
		sourceUrl: 'https://github.com/JawherKl/angular-ng-select-customize',
		status: 'completed',
	},
	{
		id: 18,
		image: Project7,
		title: 'Angular Piechart Customize',
		category: 'Website',
		demoUrl: 'https://github.com/JawherKl/angular-piechart-customize',
		sourceUrl: 'https://github.com/JawherKl/angular-piechart-customize',
		status: 'completed',
	},
	// DevOps Projects
	{
		id: 19,
		image: Project3,
		title: 'DevOps Guide',
		category: 'Devops',
		demoUrl: 'https://github.com/JawherKl/devops-guide',
		sourceUrl: 'https://github.com/JawherKl/devops-guide',
		status: 'completed',
	},
	{
		id: 20,
		image: Project3,
		title: 'ArgoCD App',
		category: 'Devops',
		demoUrl: 'https://github.com/JawherKl/argocd-app',
		sourceUrl: 'https://github.com/JawherKl/argocd-app',
		status: 'completed',
	},
	{
		id: 21,
		image: Project3,
		title: 'K8s Demo',
		category: 'Devops',
		demoUrl: 'https://github.com/JawherKl/k8s-demo',
		sourceUrl: 'https://github.com/JawherKl/k8s-demo',
		status: 'completed',
	},
	{
		id: 22,
		image: Project3,
		title: 'K8s Mongo App',
		category: 'Devops',
		demoUrl: 'https://github.com/JawherKl/k8s-mongo-app',
		sourceUrl: 'https://github.com/JawherKl/k8s-mongo-app',
		status: 'completed',
	},
	{
		id: 23,
		image: Project3,
		title: 'K8s Mongo App',
		category: 'Devops',
		demoUrl: 'https://github.com/JawherKl/domain-automation-api',
		sourceUrl: 'https://github.com/JawherKl/domain-automation-api',
		status: 'completed',
	},
	// AI/ML Projects
	{
		id: 24,
		image: null,
		title: 'AI Models Integration',
		category: 'AI/ML',
		demoUrl: 'https://github.com/JawherKl/ai-models-integration',
		sourceUrl: 'https://github.com/JawherKl/ai-models-integration',
		status: 'completed',
	},
	{
		id: 25,
		image: Project9,
		title: 'AI Faq Bot',
		category: 'AI/ML',
		demoUrl: 'https://github.com/JawherKl/ai-faq-bot',
		sourceUrl: 'https://github.com/JawherKl/ai-faq-bot',
		status: 'in-progress',
	},
	{
		id: 26,
		image: Project9,
		title: 'Machine Learning Algorithme',
		category: 'AI/ML',
		demoUrl: 'https://github.com/jawherr/machine-learning-algorithme',
		sourceUrl: 'https://github.com/jawherr/machine-learning-algorithme',
		status: 'in-progress',
	},
	// Contributions
	{
		id: 27,
		image: null,
		title: 'Developer Roadmap Contribution',
		category: 'Contributions',
		demoUrl: 'https://github.com/JawherKl/developer-roadmap',
		sourceUrl: 'https://github.com/JawherKl/developer-roadmap',
		status: 'in-progress',
	},
	{
		id: 28,
		image: null,
		title: 'Git Ignore Contribution',
		category: 'Contributions',
		demoUrl: 'https://github.com/JawherKl/gitignore',
		sourceUrl: 'https://github.com/JawherKl/gitignore',
		status: 'in-progress',
	},
	// Research
	{
		id: 29,
		image: Project2,
		title: 'Design Patterns in Multiple Languages',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/design-patterns-in-multiple-languages',
		sourceUrl: 'https://github.com/JawherKl/design-patterns-in-multiple-languages',
		status: 'completed',
	},
	{
		id: 30,
		image: Project2,
		title: 'REST GraphQL gRPC',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/REST-GraphQL-gRPC',
		sourceUrl: 'https://github.com/JawherKl/REST-GraphQL-gRPC',
		status: 'completed',
	},
	{
		id: 31,
		image: Project2,
		title: 'Database Fundamentals',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/database-fundamentals',
		sourceUrl: 'https://github.com/JawherKl/database-fundamentals',
		status: 'completed',
	},
	{
		id: 32,
		image: Project2,
		title: 'C4 Diagram',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/C4-Diagram',
		sourceUrl: 'https://github.com/JawherKl/C4-Diagram',
		status: 'completed',
	},
	{
		id: 33,
		image: Project2,
		title: 'Clustering',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/Clustering',
		sourceUrl: 'https://github.com/JawherKl/Clustering',
		status: 'completed',
	},
	{
		id: 34,
		image: Project2,
		title: 'Content Delivery Network CDN',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/Content-Delivery-Network-CDN',
		sourceUrl: 'https://github.com/JawherKl/Content-Delivery-Network-CDN',
		status: 'completed',
	},
	{
		id: 35,
		image: Project2,
		title: 'Load Balancing',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/Load-Balancing',
		sourceUrl: 'https://github.com/JawherKl/Load-Balancing',
		status: 'completed',
	},
	{
		id: 36,
		image: Project2,
		title: 'Caching',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/Caching',
		sourceUrl: 'https://github.com/JawherKl/Caching',
		status: 'completed',
	},
	{
		id: 37,
		image: Project2,
		title: 'Caching',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/Domain-Name-System-DNS',
		sourceUrl: 'https://github.com/JawherKl/Domain-Name-System-DNS',
		status: 'completed',
	},
	{
		id: 38,
		image: Project2,
		title: 'TypeScript Advanced Features',
		category: 'Research',
		demoUrl: 'https://github.com/JawherKl/typescript-advanced-features',
		sourceUrl: 'https://github.com/JawherKl/typescript-advanced-features',
		status: 'completed',
	},
];

export const projectsNav = [
	{ name: 'all' },
	{ name: 'API' },
	{ name: 'Website' },
	{ name: 'Devops' },
	{ name: 'AI/ML' },
	{ name: 'Contributions' },
	{ name: 'Research' },
];